### PR TITLE
Chore: stop to :use packages

### PR DESCRIPTION
**Pull request by kilianmh**
- stop to `use` transitive dependencies
- `import-from` utilized symbols instead

### CODE REVIEW

**Comment by hanshuebner** [comment]
Rather than importing the symbols, it would be preferable to qualify their usage.  I would not merge this PR as it does not add any value but makes future changes harder.

**Comment by kilianmh** [comment]
The main importance is to not `:use` other packages.

> it would be preferable to qualify their usage

Now the symbols from external packages are qualified instead of being imported in the defpackage. @hanshuebner 

On Linux with SBCL-2.3.2 and Allegro-10.1 loading and testing works fine. Especially on Lispworks it should be tested whether it works. (due to when-let from alexandria/lw)

**Comment by hanshuebner** [comment]
> The main importance is to not :use other packages.

I fail to see the importance at this point, but now the change looks more maintainable than the previous explicit imports.

**Comment by stassats** [comment]
Seems like a non-issue. We'll deal with any potential future conflicts when they arise.

**Pull request closed without merging**
