### PR TITLE
update instance on random port

### PR DESCRIPTION
**Pull request by drurowin**
When the port 0 is requested the system picks a random available port
for the socket.  Update the instance with whatever port the system
picks.

### CODE REVIEW

**Comment by stassats** [comment]
What happens when you stop the acceptor and then start it again?

**Comment by hanshuebner** [comment]
I like the added functionality.  In addition to addressing Stas' question,
please also update the documentation to describe that 0 can be used as
listening port to make the system select a random port.

Thanks!

**Comment by drurowin** [comment]
When you call STOP then START you'll get the same port that was chosen by the system. You'd need to call REINITIALIZE-INSTANCE with :PORT 0 to have the system pick the port again.

**Comment by hanshuebner** [comment]
The behavior of keeping the previously randomly picked port number across
stop/start may be undesirable.  I guess that the random port number is
mostly useful for testing purposes, where the test wants to initiate a
server on a free port - At least that is the guarantee of the new API
functionality.  When the port number is retained across stop/restart,
however, the same port number may no longer be free when the server is
restarted.  This could be the desired behavior, or it could not.  Whatever
you desire to achieve, please document the start/stop behavior so that it
is clear what's happening.

**Comment by hanshuebner** [comment]
merged, thanks!

**Pull request merged**
