### PR TITLE
Increase performance by 7% by not re-asking the same data.

### PR DESCRIPTION
**Pull request by phmarek**
Going to kernel-space is expensive; even more so after the
recent SPECTRE/MELTDOWN mitigations. Just caching the remote
and local socket addresses already gives a nice boost.

Measurements via "wrk --latency <URL>", before and after:
  104008 requests in 10.00s, 99.98MB read
vs.
  111069 requests in 10.00s, 106.77MB read

### CODE REVIEW

**Comment by vityok** [comment]
Looks good. I'd merge it in. Is anyone against?

**Comment by stassats** [comment]
It doesn't look good.
```
(multiple-value-bind (remote-addr remote-port)
      (or remote (get-peer-address-and-port socket))
```
It is losing remot-port.

**Comment by phmarek** [comment]
Yeah, right. Sorry about that.

Fixed in newer version.

**Comment by stassats** [comment]
That's better, but I'd prefer it to be a LET instead of LET+SETF.

**Comment by phmarek** [comment]
I had these down there by design, to keep them with `*hunchentoot-stream*`...

Here's the version without `SETF`.

**Pull request merged**
