### PR TITLE
Three updates for HT.

### PR DESCRIPTION
**Pull request by phmarek**
Thank you!

### CODE REVIEW

**Comment by stassats** [comment]
Does "Respect the "Content-Length" header when parsing form data." still just produces an error?

**Comment by stassats** [comment]
create-folder-dispatcher-and-handler is exported, changing from &optional to &key is a no go.

**Comment by stassats** [comment]
So what happens with Content-length: 0? Does it still work?

**Comment by stassats** [comment]
Compared to #164

**Comment by stassats** [comment]
So?

**Comment by phmarek** [comment]
Sorry about the delay. I haven't forgotten, I just don't find a large enough block of time to concentrate on that.
I'm running that code in my setup, and even the "Content-length: 0" requests from Firefox are correctly handled (no hang, no error, just no file contents being seen by the hunchentoot handler); but I wanted to do some more manual tests, and perhaps even drop some automated tests in.

**Comment by phmarek** [comment]
Oh, thanks a lot!

**Pull request merged**
