### PR TITLE
Add valid-external-format-name-p

### PR DESCRIPTION
**Pull request by lispalien**
When hunchentoot receives a post request with a content-type including a
charset, it always falls back to the default external format with a
warning like:

WARNING: Ignoring unknown character set utf-8 in request content type.

This is because parse-content-type returns strings, but
make-external-format expects a keyword symbol. The function
valid-external-format-name-p checks the charset string against the
symbols acceptable to make-external-format, returning the symbol.

### CODE REVIEW

**Comment by hanshuebner** [comment]
We cannot rely on internal symbols of flexi-streams that way.  Are you sure that your analysis is correct?  Would that not mean that in the past, only POST requests with the default external format would have worked?  I am not saying that this can't be the case, but it leaves me wondering why this bug has not been detected before.

**Comment by lispalien** [comment]
It was unsettling to use internal symbols like that; perhaps flexi-streams should be patched to cope with a string charset identifier instead. Happy to rework it - is there anything you'd like to see done differently like a hash-table instead of alist scanning?

I'm confident that when a post request has a charset specified, hunchentoot parses out the charset identifier as a string, passes that string to make-external-format, and that a string is not acceptable to it.

**Comment by hanshuebner** [comment]
I think this would better be implemented as a patch to flexi-streams that makes it more flexible regarding the arguments that `flex:make-external-format accepts` (i.e. strings in addition to keywords).  If the arguments can not be resolved to a valid external format, the function should signal a well known condition that can be specifically caught by application programs.

**Comment by lispalien** [comment]
I'll make it so, cheers

**Pull request closed without merging**
